# Model Architecture
model:
  name: "CustomVGG"
  pretrained: true
  num_classes: 2
  num_neurons: 64
  activation: "ReLU"

# Training Parameters
training:
  batch_size: 32
  learning_rate: 0.001
  epochs: 10
  target_accuracy: 0.98
  early_stopping_patience: 5
  class_weights: [1, 3]  # [good, anomaly]

# Data Parameters
data:
  input_size: [224, 224]
  train_categories: ["capsule", "hazelnut", "leather"]
  test_categories: ["bottle", "pill", "wood"]
  test_size: 0.2
  random_state: 42

# Experiment Parameters
experiment:
  activations: ["ReLU", "Tanh"]
  num_neurons_list: [64, 128]
  learning_rates: [0.001, 0.0001]
  optimizers: ["Adam", "SGD"]
  batch_sizes: [32, 64]
  epochs_list: [10, 20]

# Paths
paths:
  data_dir: "data"
  weights_dir: "weights"
  results_dir: "results"
  plots_dir: "results/plots"
  metrics_dir: "results/metrics" 